name: Deploy Alpine VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      OS_PASSWORD: ${{ secrets.MICROSTACK }}
    steps:
      - uses: actions/checkout@v4

      - name: Make deploy_vm.sh executable
        run: chmod +x scripts/deploy_vm.sh

      - name: Deploy Alpine VM
        shell: bash
        run: ./scripts/deploy_vm.sh
