name: Deploy Alpine VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenStack client
        run: |
          sudo apt update
          sudo apt install -y python3-openstackclient

      - name: Load OpenStack credentials
        run: |
          echo "OS_AUTH_URL=${{ secrets.OS_AUTH_URL }}" >> $GITHUB_ENV
          echo "OS_USERNAME=${{ secrets.OS_USERNAME }}" >> $GITHUB_ENV
          echo "OS_PASSWORD=${{ secrets.OS_PASSWORD }}" >> $GITHUB_ENV
          echo "OS_PROJECT_NAME=${{ secrets.OS_PROJECT_NAME }}" >> $GITHUB_ENV
          echo "OS_USER_DOMAIN_NAME=Default" >> $GITHUB_ENV
          echo "OS_PROJECT_DOMAIN_NAME=Default" >> $GITHUB_ENV

      - name: Deploy VM
        run: |
          sudo chmod +x scripts/deploy_vm.sh
          ./scripts/deploy_vm.sh
